name: Home Assistant CI/CD

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  tests:
    runs-on: ubuntu-latest
    env:
      NODE_ENV: test
      DEV_FRONTEND_SERVER: ${{ secrets.DEV_FRONTEND_SERVER }}
      PROD_FRONTEND_SERVER: ${{ secrets.PROD_FRONTEND_SERVER }}
      PORT: ${{ secrets.PORT }}
      HA_API_URL: ${{ secrets.HA_API_URL }}
      HA_ACCESS_TOKEN: ${{ secrets.HA_ACCESS_TOKEN }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install node modules
        run: npm install
      
      - name: Run tests 
        run: npm test
      
      - name: Install Fly CLI
        uses: superfly/flyctl-actions/setup-flyctl@master

      - name: Deploy to Fly
        run: flyctl deploy --remote-only
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
